### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by kschultee** [kschultee/tunesGoons#14]
### Motivation 
Refactoring increases readability and maintainability of the code base.

### Tasks 
- [x] Server refactoring.
  - [x] Add error handling middleware.
  - [x] Create Spotify service object module.
- [x] Client refactoring.
  - [x] Make client/services folder.
  - [x] Create module to hold API service.
  - [x] Create transport module to hold player fetch requests.
  - [x] Create method for all transport controls on the API service.
  - [x] Move transport controls into Media component.
  - [x] Check singular vs. plural variable names.
  - [x] Practice "tell don't ask".
